---
- name: Initiate Nexus Dashboard Insights - Pre-Change Delta Analysis
  hosts: nd
  gather_facts: false
  vars:
    insights_group: MEL-SE-LAB-ACI
    job_name: ANSIBLE-CICD-PCV
    site_name: MEL-SE-LAB-ACI
    input_file: config.json
  roles:
    - role: ndi-pcv
